[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "AdvancedMachines"
versionNumber = "2.4.2"
description = "Adds MKIII/MKIV/MKV versions of Smelters, Assemblers, Drills, Threshers, and Planters. Properly tiered: MKIII=Floor2, MKIV=Floor3, MKV=Floor4."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-AdvancedMachines"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/AdvancedMachines.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]


